### ISSUE TITLE
Use Arc instead of Rc for sharing between threads

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/cudarc#10]

**Comment by M1ngXU** [comment]
we have to be very careful if using the same handle from multiple threads is allowed. (e.g. it isn't for cudnn while it is for cublas)

**Comment by coreylowman** [comment]
Yeah that's great to know - we'll probably have to be somewhat specific on what things we can wrap in Arc and what will be wrapped in Rc. thanks for the info

**Comment by coreylowman** [comment]
Everythign is using arc now
