### ISSUE TITLE
Add occupancy apis to driver/result and driver/safe

### ISSUE THREAD

**Issue by chelsea0x3b** [coreylowman/cudarc#102]
Detailed here https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__OCCUPANCY.html#group__CUDA__OCCUPANCY

**Comment by Jark5455** [comment]
can we get an update on this? is there a pr?

**Comment by coreylowman** [comment]
Addressed by pr above, thanks @Jark5455 !
