### ISSUE TITLE
How to copy a device repr struct where one of the fields is an pointer representing an array of floats?

### ISSUE THREAD

**Issue by l3utterfly** [coreylowman/cudarc#128]
Using the "device_repr" example, if I modify my struct to contain a pointer representing an array. Like this:

In Rust:
````
#[repr(C)]
pub struct MyStruct {
    pub arr: *mut f32,
    pub length: ::std::os::raw::c_uint,
}
````

In CU:
````
struct MyStruct 
{
    float *arr;

    // length
    unsigned int length;
}
````

Using the same code, I can get the "length" field in CUDA just fine. However, when I try to access any element of the array using `myStruct.arr[i]`, I get an illegal memory access exception in CUDA.

This is how I'm initialising the struct in Rust:
````
let my_struct = MyStruct {
        length: 4,
        arr: vec![1.0f32, 1.0f32, 1.0f32, 1.0f32].as_mut_ptr(),
    };
````

**Comment by M1ngXU** [comment]
the `arr` field point to a location in the cpu memory. this is probably not accessible by the gpu. you should instead use cuda slices and use their pointers.

**Comment by l3utterfly** [comment]
Thank, this works.
