### ISSUE TITLE
NCCL support

### ISSUE THREAD

**Issue by chaserileyroberts** [coreylowman/cudarc#129]
We should add [NCCL](https://developer.nvidia.com/nccl) support for multi-gpu computation and communication. I'd be happy to try to take this up as a first contribution.

**Comment by chaserileyroberts** [comment]
#164 Finished this for me. 🙇🏼

**Comment by jedbrown** [comment]
I've had in mind to make a simple interface for creating a NCCL communicator from an MPI communicator, similar to [these examples](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/examples.html#example-2-one-device-per-process-or-thread). I think that would belong in cudarc under a feature flag (that would create an optional dependency on [rsmpi](https://github.com/rsmpi/rsmpi/)).
