### ISSUE TITLE
Possible to use #![feature(abi_ptx)]?

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/cudarc#143]
Using https://doc.rust-lang.org/unstable-book/language-features/abi-ptx.html, you can compile rust functions to PTX on nightly compiler. How can we use this with cudarc?

**Comment by ViliamVadocz** [comment]
Looking at the tracking issue https://github.com/rust-lang/rust/issues/38788, the feature seems to be in very early stages. It looks very exciting, but maybe not usable yet?

**Comment by ariasanovsky** [comment]
@ViliamVadocz [Here](https://gist.github.com/ariasanovsky/320ecc81948b73f998a39362920c0780) I build rs into ptx separately with `xargo` and nightly Rust.

I haven't been able to replace the `let ptx = compile_ptx(KERNEL_SRC).unwrap();` lines in [this example](https://github.com/coreylowman/cudarc/blob/1c29f4941685ffe2ec6ac80c0ec6b86ce257c435/examples/06-threading.rs) with `let ptx = Ptx::from_file(r"path\to\ptx-number.s");` yet. I get `Error: DriverError(CUDA_ERROR_INVALID_PTX, "a PTX JIT compilation failed")`.

**Comment by ariasanovsky** [comment]
MVP here! https://github.com/ariasanovsky/cuda-loop @coreylowman
