### ISSUE TITLE
Publish new version to crates.io

### ISSUE THREAD

**Issue by ViliamVadocz** [coreylowman/cudarc#157]
Would it be possible to publish the newest version of this library to crates.io?

I would like to publish https://github.com/ViliamVadocz/nvidia-video-codec-sdk which uses this library, but I cannot while I specify the dependency using git. I am using the features introduced in #152 and #155, which are only available on git right now.

P.S. I'm glad to see you're back @coreylowman. I hope all your life things have gone well 😄.

**Comment by coreylowman** [comment]
Released v0.9.10!
