### ISSUE TITLE
Issue on passing of host to device parameters

### ISSUE THREAD

**Issue by swfsql** [coreylowman/cudarc#193]
Hi, I'm a very beginner on cuda, and while studying this library and some cuda docs, I think that there can be a mistake in using host primitive data as cuda kernel parameters.  
Sorry in advance if this unfounded!

The [sc11-cuda-c-basics](https://www.nvidia.com/docs/io/116711/sc11-cuda-c-basics.pdf) doc, on page 19, mention that all parameters on a cuda device kernel must be pointer and also that those pointers refer to allocations on the gpu device. When reading some kernel implementations on dfdx, I noticed that some parameters aren't pointers, such as in:

https://github.com/coreylowman/dfdx/blob/4476b5ee19dc9cc446388545560c57e80cb086c8/dfdx-core/src/tensor_ops/sgd/sgd.cu#L23-L30

From the rust-host side, what is allowing those values to be passed is the `DeviceRepr` impl, where this is an example below:
https://github.com/coreylowman/cudarc/blob/42f8f861ca1c9e586ff695efb29bd3719a2802a7/src/driver/safe/alloc.rs#L30

The default impl gets the rust-host data location and recasts into a pointer, but this data wasn't allocated (nor copied, in this case) into the gpu device:
https://github.com/coreylowman/cudarc/blob/42f8f861ca1c9e586ff695efb29bd3719a2802a7/src/driver/safe/alloc.rs#L16-L21

The implementation for `CudaSlice` appears to also recast into a pointer, but it recasts a memory location that (I think) was already existing in the gpu device:
https://github.com/coreylowman/cudarc/blob/42f8f861ca1c9e586ff695efb29bd3719a2802a7/src/driver/safe/alloc.rs#L43-L48

From what I read from the code and it's docs, the parameters are ultimately organized into an array of pointers and this is passed into the [cuLaunchKernel](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__EXEC.html#group__CUDA__EXEC_1gb8f3dc3031b40da29d5f9a7139e52e15), but when looking into online examples of calling this function, such as [this](https://stackoverflow.com/a/75075473), it appears that the host should ensure that all pointers were `CUdeviceptr` before being passed in.

I apologize if there's actually no problem, and if there is I'm not sure what would be the best way moving forward if what was appointed here is correct. But anyway, thanks for reading!

**Comment by aryan-programmer** [comment]
If we check the official NVidia CUDA Samples, then in the `vectorAdd_nvrtc` sample at the following line, we see 

https://github.com/NVIDIA/cuda-samples/blob/e8568c417356f7e66bb9b7130d6be7e55324a519/Samples/0_Introduction/vectorAdd_nvrtc/vectorAdd.cpp#L113

```C++
  void *arr[] = {reinterpret_cast<void *>(&d_A), reinterpret_cast<void *>(&d_B),
                 reinterpret_cast<void *>(&d_C),
                 reinterpret_cast<void *>(&numElements)};
```

Here, `numElements` is defined on the Host's stack (line 62) and this program works just fine, and outputs: 

```
sdkFindFilePath <vectorAdd_kernel.cu> in ./
> Using CUDA Device [0]: NVIDIA GeForce GTX 1660 SUPER
> Using CUDA Device [0]: NVIDIA GeForce GTX 1660 SUPER
> GPU Device has SM 7.5 compute capability
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```



If we look the the link to the documentation for [`[cuLaunchKernel](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__EXEC.html#group__CUDA__EXEC_1gb8f3dc3031b40da29d5f9a7139e52e15) `](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__EXEC.html#group__CUDA__EXEC_1gb8f3dc3031b40da29d5f9a7139e52e15), then we see:       

> Kernel parameters can be specified via `kernelParams`. If `f` has N parameters, then `kernelParams` needs to be an array of N pointers. Each of `kernelParams[0]` through `kernelParams[N-1]` must point to a region of memory from which the actual kernel parameter will be copied. The number of kernel parameters and their offsets and sizes do not need to be specified as that information is retrieved directly from the  kernel's image.

The key point here is the 2nd to last sentence: The elements of the `kernelParams` array are **not** the actual kernel parameters. They only **point** to the actual kernel parameters.

Then the device infers the size of the kernel parameters from the definition of the kernel, dereferences the pointers to the kernel parameters, and copies the kernel parameters to the device automatically.

We can actually see that this is what the device does via the below code samples.

### C++ CUDA Runtime Example

```C++
#include <cstdlib>
#include <stdio.h>

#include <cuda_runtime.h>
#include <iostream>

using namespace std;

__global__ void demo(int x, int* px) {
	printf("Dev: x = %d, px = %p\n", x, px);
	//printf("Dev: x = %d, px = %p, *px = %d\n", x, px, *px);
}

int main() {
	cudaError_t err = cudaSuccess;
	int         x   = 42;
	int*        px  = &x;

	cout << "Hst: x = " << x << ", px = " << px << ", *px = " << *px << endl;
	demo<<<1,1>>>(x, &x);
	err = cudaGetLastError();
	if (err != cudaSuccess) {
		cerr << "Failed to launch kernel (error: " << cudaGetErrorString(err) << ")!" << endl;
		exit(EXIT_FAILURE);
	}
	err = cudaDeviceSynchronize();

	if (err != cudaSuccess) {
		cerr << "Failed to synchronize (error: " << cudaGetErrorString(err) << ")!" << endl;
		exit(EXIT_FAILURE);
	}
	cout << "Done" << endl;
	return 0;
}

```

Here, the output is:

```
Hst: x = 42, px = 000000D0EAEFF714, *px = 42
Dev: x = 42, px = 000000D0EAEFF714
Done
```

The values for `px` are the same, but if we try to dereference it on the device, by changing the definition of `demo` to:

```C++
__global__ void demo(int x, int* px) {
	//printf("Dev: x = %d, px = %p\n", x, px);
	printf("x = %d, px = %p, *px = %d\n", x, px, *px);
}
```

We now get:

```
Hst: x = 42, px = 00000099428FF934, *px = 42
Failed to synchronize (error: an illegal memory access was encountered)!
```

### C++ CUDA NVRTC Example

Similar example with NVRTC (Adapted from https://docs.nvidia.com/cuda/pdf/NVRTC_User_Guide.pdf):

```C++
#include <cuda.h>
#include <cuda_runtime.h>
#include <nvrtc.h>
#include <stdio.h>

#include <cstdlib>
#include <iostream>

using namespace std;

#define NVRTC_SAFE_CALL(x)                                                                   \
	do {                                                                                     \
		nvrtcResult result = x;                                                              \
		if (result != NVRTC_SUCCESS) {                                                       \
			std::cerr << "\nerror: " #x " failed with error " << nvrtcGetErrorString(result) \
					  << '\n';                                                               \
			exit(1);                                                                         \
		}                                                                                    \
	} while (0)
#define CUDA_SAFE_CALL(x)                                                     \
	do {                                                                      \
		CUresult result = x;                                                  \
		if (result != CUDA_SUCCESS) {                                         \
			const char* msg;                                                  \
			cuGetErrorName(result, &msg);                                     \
			std::cerr << "\nerror: " #x " failed with error " << msg << '\n'; \
			exit(1);                                                          \
		}                                                                     \
	} while (0)
const char* demo_code = R"(
extern "C" __global__ void demo(int x, int* px) {
	printf("Dev: x = %d, px = %p\n", x, px);
	//printf("Dev: x = %d, px = %p, *px = %d\n", x, px, *px);
}
)";

int main() {
	int  x  = 42;
	int* px = &x;

	// Create an instance of nvrtcProgram with the demo_code string.
	nvrtcProgram prog;
	NVRTC_SAFE_CALL(
		nvrtcCreateProgram(
			&prog,          // program
			demo_code,      // buffer
			"demo_code.cu", // name
			0,              // numHeaders
			NULL,           // headers
			NULL));         // includeNames
	// Compile the program with fmad disabled.
	// Note: Can specify GPU target architecture explicitly with '-arch' flag.
	const char* opts[]         = {"--fmad=false"};
	nvrtcResult compile_result = nvrtcCompileProgram(prog, 1, opts);
	// Obtain compilation log from the program.
	size_t logSize;
	NVRTC_SAFE_CALL(nvrtcGetProgramLogSize(prog, &logSize));
	char* log = new char[logSize];
	NVRTC_SAFE_CALL(nvrtcGetProgramLog(prog, log));
	if (strlen(log) > 0) {
		cout << log << '\n';
	}
	delete[] log;
	NVRTC_SAFE_CALL(compile_result);
	// Obtain PTX from the program.
	size_t ptxSize;
	NVRTC_SAFE_CALL(nvrtcGetPTXSize(prog, &ptxSize));
	char* ptx = new char[ptxSize];
	NVRTC_SAFE_CALL(nvrtcGetPTX(prog, ptx));
	// Destroy the program.
	NVRTC_SAFE_CALL(nvrtcDestroyProgram(&prog));
	// Load the generated PTX and get a handle to the demo kernel.
	CUdevice   cuDevice;
	CUcontext  context;
	CUmodule   module;
	CUfunction kernel;
	CUDA_SAFE_CALL(cuInit(0));
	CUDA_SAFE_CALL(cuDeviceGet(&cuDevice, 0));
	CUDA_SAFE_CALL(cuCtxCreate(&context, 0, cuDevice));
	CUDA_SAFE_CALL(cuModuleLoadDataEx(&module, ptx, 0, 0, 0));
	CUDA_SAFE_CALL(cuModuleGetFunction(&kernel, module, "demo"));

	cout << "Hst: x = " << x << ", px = " << px << ", *px = " << *px << endl;

	void* args[] = {&x, &px};
	CUDA_SAFE_CALL(cuLaunchKernel(
		kernel,    // f
		1,         // gridDimX
		1,         // gridDimY
		1,         // gridDimZ
		1,         // blockDimX
		1,         // blockDimY
		1,         // blockDimZ
		0,         // sharedMemBytes
		NULL,      // hStream
		args,      // kernelParams
		nullptr)); // extra
	CUDA_SAFE_CALL(cuCtxSynchronize());
	// Release resources.
	CUDA_SAFE_CALL(cuModuleUnload(module));
	CUDA_SAFE_CALL(cuCtxDestroy(context));

	cout << "Done" << endl;

	return 0;
}

```

Current output:

```
Hst: x = 42, px = 0000002580EFF584, *px = 42
Dev: x = 42, px = 0000002580EFF584
Done
```

Switching definition of `demo_code` to:

```C++
const char* demo_code = R"(
extern "C" __global__ void demo(int x, int* px) {
	//printf("Dev: x = %d, px = %p\n", x, px);
	printf("Dev: x = %d, px = %p, *px = %d\n", x, px, *px);
}
)";
```

We get:

```
Hst: x = 42, px = 00000034A3D1F6F4, *px = 42

error: cuCtxSynchronize() failed with error CUDA_ERROR_ILLEGAL_ADDRESS
```

-----
All of what I have written is true to the best of my knowledge, however I apologize for any mistakes I may have made and welcome all corrections.
