### ISSUE TITLE
Passing `u8` and `i64` to templated kernel

### ISSUE THREAD

**Issue by jeromeku** [coreylowman/cudarc#195]
2 questions:
1)  I have a templated `CUDA` kernel for types `f16, f32, f64, u8,  u32, i64`.  I've checked the kernel works in `C++ / CUDA`.  However, when launching the kernel from Rust, I get incorrect results for `u8` and `i64`.  Are there additional precautions when passing these types? 

2)  Is there an API for `cudaGetDeviceProperties`?  
    Need to implement:
    ```c++
    inline int getMaxThreadsPerBlock()
    {
        int device;
        cudaDeviceProp props;
        cudaGetDevice(&device);
        cudaGetDeviceProperties(&props, device);
        return props.maxThreadsPerBlock;
    }
    ```

**Comment by coreylowman** [comment]
You can't interact with templated kernels from rust unfortuntely - you'll either have to have wrapper function for each type you want to use across the boundary, or do JIT compilation at runtime and paste in the name of the type into the kernel implementation string.

You can use the driver version of the api instead:
```rust
unsafe fn get_max_threads_per_block(ordinal: usize) -> Result<i32, DriverError> {
    let cu_device = result::device::get(ordinal as i32).unwrap();
    result::device::get_attribute(
                cu_device,
                sys::CUdevice_attribute_enum::CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_BLOCK
    )
}
```

feel free to reopen or ask further questions here if you want. will close for now
