### ISSUE TITLE
Add `cudaFuncSetAttribute`

### ISSUE THREAD

**Issue by EricLBuehler** [coreylowman/cudarc#203]
Hello @coreylowman,

I have been working on `candle-vllm` and realized their implementation used `cudaFuncSetAttribute` and `cudaFuncAttributeMaxDynamicSharedMemorySize` to set the max shared memory size. How could I emulate this behavior in Rust using this framework?

**Comment by guoqingbao** [comment]
> Hello @coreylowman,
> 
> I have been working on `candle-vllm` and realized their implementation used `cudaFuncSetAttribute` and `cudaFuncAttributeMaxDynamicSharedMemorySize` to set the max shared memory size. How could I emulate this behavior in Rust using this framework?

You may use cuFuncSetAttribute and cuFuncSetSharedMemConfig in this crate. See this: https://github.com/coreylowman/cudarc/blob/main/src/driver/sys.rs.
