### ISSUE TITLE
rename CudaError -> DeviceError

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/cudarc#22]

**Comment by M1ngXU** [comment]
why exactly? could we also have a general cudarc error using some crate like anyhow (never really used it, so idk if it’s the best one)? sometimes creating these enums holding all kind of errors types is a pain … (just to not panic in a function and bubble up the errors)

**Comment by coreylowman** [comment]
dfdx will also have an error type for cuda, likely named CudaError. This specific error right now isn't a generic cuda error that covers anything in cuda world, its just a driver error. Maybe DriverError would be a better name

**Comment by M1ngXU** [comment]
Ok
