### ISSUE TITLE
New crates.io release?

### ISSUE THREAD

**Issue by jafioti** [coreylowman/cudarc#222]
Hi corey,
Do you have an approximate time you're thinking about cutting a new crates.io release?

**Comment by jafioti** [comment]
@coreylowman

**Comment by coreylowman** [comment]
Will release over next couple of days - will address a couple of the new issues & want to fix an issue with nccl on older cuda versions & then release

**Comment by coreylowman** [comment]
Actually nvm, just released 0.11.0
