### ISSUE TITLE
Are there any break changes soon?

### ISSUE THREAD

**Issue by Garrybest** [coreylowman/cudarc#237]
I'm planning to use `cudarc` as a tool for my rust project to invoke cuda. I see this sentence in README.md.

```
Pre-alpha state, expect breaking changes and not all cuda functions contain a safe wrapper. 
```

Are there any break changes soon? When is it releassed? It could infect my decision of developing plan.

**Comment by coreylowman** [comment]
Not any wide revamps planned. I'm trying to be very strict with what I consider a breaking change - e.g. all of these are breaking changes and will result in a minor version number bump:
- public function signature change
- Changes to a public trait (e.g. https://github.com/coreylowman/cudarc/pull/221)
- Changes to default features in cargo.toml
Any breaking changes will be reported in the release announcement, and shouldn't take more than an hour to update.

And also you don't have to update to the latest version - if the version you pick works for you, you can just stick with that.
