### ISSUE TITLE
Issue for building my rust application with cudarc v0.11.1 (Unsupported cuda toolkit version: `10010`)

### ISSUE THREAD

**Issue by jay11ca39** [coreylowman/cudarc#239]
I am using: **cudarc v0.11.1**

It is giving weird error: 

```
error: failed to run custom build command for `cudarc v0.11.1`
Unsupported cuda toolkit version: `10010`. Please raise a github issue.
```

I have removed all cuda-toolkit, installed freshly and rebooted my machine : 
Following is my cuda toolkit details: 
**$ nvcc --version**

> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2024 NVIDIA Corporation
> Built on Wed_Apr_17_19:19:55_PDT_2024
> Cuda compilation tools, release 12.5, V12.5.40
> Build cuda_12.5.r12.5/compiler.34177558_0

**$ nvidia-smi**

Thu May 30 11:09:47 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro P400                    Off |   00000000:9E:00.0 Off |                  N/A |
| 34%   36C    P8             N/A /  N/A  |     243MiB /   2048MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      2482      G   /usr/lib/xorg/Xorg                             69MiB |
|    0   N/A  N/A      2620      G   /usr/bin/gnome-shell                          126MiB |
+-----------------------------------------------------------------------------------------+

Even i treid for CUDA different versions.

**Comment by coreylowman** [comment]
Currently we extract the version from the cuda.h file present on the system. We should move to either extracting from nvcc or nvidia-smi. Likely just running `nvcc --version` from build.rs and extracting the version from that.
