### ISSUE TITLE
Not able to include <stddef.h> + etc. when compiling?

### ISSUE THREAD

**Issue by brandonros** [coreylowman/cudarc#263]
If I use `nvcc`, things like

```c
#include <stdio.h>
#include <stddef.h>
#include <stdlib.h>
#include <memory.h>
```

work fine.

If I use

```rust
fn device_thread(device_index: usize, lowest_target_seen: Arc<RwLock<Vec<u8>>>) -> Result<(), Box<dyn Error>> {
    // get device
    let device = cudarc::driver::CudaDevice::new(device_index)?;

    // bind to thread
    device.bind_to_thread()?;

    // compile program
    log::info!("device_index = {device_index} compiling...");
    let ptx = cudarc::nvrtc::compile_ptx_with_opts(include_str!("./kernel.cu"), cudarc::nvrtc::CompileOptions {
        include_paths: vec![
            "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.5\\include\\".into(),
            "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.5\\include\\cuda\\std\\detail\\libcxx\\include\\".into(),
        ],
        ..Default::default()
    })?;
    device.load_ptx(ptx, "my_module", &["try_hashes_kernel"])?;
    log::info!("device_index = {device_index} compiled");
```

(I've tried all variations of with + without include paths), I get no luck... Is this something that could be clarified better with an example/documentation? Am I doing something wrong or is this expected?

**Comment by brandonros** [comment]
As a workaround for anybody who lands on this,

make sure the exported symbol (your kernel) you want is marked `extern "C" __global__`

then

`nvcc -keep kernel.cu`

then

`device.load_ptx(cudarc::nvrtc::Ptx::from_file("./kernel/kernel.ptx"), "my_module", &["try_hashes_kernel"])?;`

**Comment by coreylowman** [comment]
Where are those files that you tried to include located on your system? It likely is some difference in default include paths for nvrtc and nvcc
