### ISSUE TITLE
cudarc fails to load libraries on official nvidia ubuntu images

### ISSUE THREAD

**Issue by manifest** [coreylowman/cudarc#274]
docker image: [`nvidia/cuda:12.5.1-runtime-ubuntu24.04`](https://hub.docker.com/layers/nvidia/cuda/12.5.1-runtime-ubuntu24.04/images/sha256-37a25acfc46f9ec05b7131639ed9467810b45522a3dfa99038635ed73c3f1e3c?context=explore)
cudarc version: `0.11.7`

Error message:
```
Unable to dynamically load the "cublas" shared library - searched for library names: ["cublas", "cublas64", "cublas64_12", "cublas64_125", "cublas64_125_0", "cublas64_120_5", "cublas64_10", "cublas64_120_0", "cublas64_9"]. Ensure that `LD_LIBRARY_PATH` has the correct path to the installed library. If the shared library is present on the system under a different name than one of those listed above, please open a GitHub issue.
```

Location of the libraries on `nvidia/cuda:12.5.1-runtime-ubuntu24.04`:
```bash
/usr/local/cuda/targets/x86_64-linux/lib/libOpenCL.so.1
/usr/local/cuda/targets/x86_64-linux/lib/libcublas.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libcufft.so.11
/usr/local/cuda/targets/x86_64-linux/lib/libcufftw.so.11
/usr/local/cuda/targets/x86_64-linux/lib/libcufile.so.0
/usr/local/cuda/targets/x86_64-linux/lib/libcufile_rdma.so.1
/usr/local/cuda/targets/x86_64-linux/lib/libcurand.so.10
/usr/local/cuda/targets/x86_64-linux/lib/libcusolver.so.11
/usr/local/cuda/targets/x86_64-linux/lib/libcusolverMg.so.11
/usr/local/cuda/targets/x86_64-linux/lib/libcusparse.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnppc.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnppial.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnppicc.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnppidei.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnppif.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnppig.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnppim.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnppist.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnppisu.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnppitc.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnpps.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnvJitLink.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnvblas.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnvfatbin.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnvjpeg.so.12
/usr/local/cuda/targets/x86_64-linux/lib/libnvrtc-builtins.so.12.5
/usr/local/cuda/targets/x86_64-linux/lib/libnvrtc.so.12
```

**Comment by coreylowman** [comment]
Hmm I've always used the cuda devel docker images (e.g. [12.5.1-cudnn-devel-ubuntu20.04](https://hub.docker.com/layers/nvidia/cuda/12.5.1-cudnn-devel-ubuntu20.04/images/sha256-c8de9fb4fa94fd1e3623013f73e1538d9bc5eb2f7469665e62ab22652a0eeddd?context=explore)) and those have worked for me.

Can you try the devel images? If runtime images are necessary for you I can look into why they are different (I'm thinking the .12 at the end of the library name is messing up the dynamic loading searching).

Alternatively - You can disable dynamic loading in favor of using dynamic linking, and that will likely work.

**Comment by manifest** [comment]
> Can you try the devel images? If runtime images are necessary for you I can look into why they are different (I'm thinking the .12 at the end of the library name is messing up the dynamic loading searching).

That could be the reason, because creating symlinks for the libraries above resolves the issue on runtime image. That work around works, but I would love to get rid of it :-)

We use devel image for the first build stage and then move binary to the runtime image to keep the image size small.

> Hmm I've always used the cuda devel docker images (e.g. 12.5.1-cudnn-devel-ubuntu20.04) and those have worked for me.

We used `nvidia/cuda:11.8.0-runtime-ubuntu22.04` with cudarc `0.10.0` and it worked fine. After upgrade to cudarc `0.11.7`, we've got the problem.

I would have tested cudarc `0.11.7` against `cuda:11`, but some other dependency in our application now requires `cuda:12`.

**Comment by manifest** [comment]
> Can you try the devel images?

I've just tried `nvidia/cuda:12.5.1-devel-ubuntu24.04`, it works fine.

> Alternatively - You can disable dynamic loading in favor of using dynamic linking, and that will likely work.

How can I do that? We use `cudarc` as a dependency of [`candle`](https://github.com/huggingface/candle).

**Comment by coreylowman** [comment]
Hmm looks like the main branch of candle is using dynamic linking already - are ya'll on an older version or a branch?

Also FYI there was a bug with 0.11.7, so recommend either upgrading to 0.11.8 or downgrading to 0.11.6 (which is the version candle is targetting).

I'll play around and see if I can get the dynamic loader to account for postfixes to the path. I'm not sure if we have that much control over pre & post fixes though (e.g. adding a `.<major>` after the `.so`), so symlinks may have to suffice for now.

**Comment by manifest** [comment]
I've upgraded to 0.11.8.

In logs, I see only the following message. The same message as before.
```bash
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cudarc-0.11.8/src/lib.rs:98:5:
Unable to dynamically load the "cublas" shared library - searched for library names: ["cublas", "cublas64", "cublas64_12", "cublas64_125", "cublas64_125_0", "cublas64_120_5", "cublas64_10", "cublas64_120_0", "cublas64_9"]. Ensure that `LD_LIBRARY_PATH` has the correct path to the installed library. If the shared library is present on the system under a different name than one of those listed above, please open a GitHub issue.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by coreylowman** [comment]
Ah yeah, sorry for miscommunicating - upgrading to 0.11.8 won't fix the message in this issue

**Comment by manifest** [comment]
I've got you. Just wanted to clarify that I on the latest version in case you want me to test something :-)

**Comment by maulberto3** [comment]
Wondering if [LibreCuda](https://github.com/mikex86/LibreCuda) might help?

**Comment by manifest** [comment]
I've built `candle` with `cudarc` from the master branch. This issue has been resolved by [the latest commit](https://github.com/coreylowman/cudarc/commit/d7ac2b481cb637f7a73f2520ff2d12809285133f). Thanks.

@coreylowman  Are you planning on making a release?

**Comment by manifest** [comment]
[Fixed](https://github.com/coreylowman/cudarc/commit/d7ac2b481cb637f7a73f2520ff2d12809285133f)

**Comment by polarathene** [comment]
Just adding this response to clarify this concern:

> BTW I don't see the driver library `libcuda.so`, it seems like the docker image only has the runtime library (`libcudart.so`).

For reference it lives in a separate location: `/usr/local/cuda/compat/`

```console
$ du -hx --si /usr/local/cuda/compat/*

0       /usr/local/cuda/compat/libcuda.so
0       /usr/local/cuda/compat/libcuda.so.1
30M     /usr/local/cuda/compat/libcuda.so.535.129.03
0       /usr/local/cuda/compat/libcudadebugger.so.1
11M     /usr/local/cuda/compat/libcudadebugger.so.535.129.03
0       /usr/local/cuda/compat/libnvidia-nvvm.so
0       /usr/local/cuda/compat/libnvidia-nvvm.so.4
87M     /usr/local/cuda/compat/libnvidia-nvvm.so.535.129.03
0       /usr/local/cuda/compat/libnvidia-ptxjitcompiler.so.1
24M     /usr/local/cuda/compat/libnvidia-ptxjitcompiler.so.535.129.03
```

Then when running a container with host GPU support, `libcuda` is mounted into the container from the host system and some other mounts IIRC (_visible via `findmnt` or `df --all` commands_):

```console
$ docker run --rm -it --gpus all fedora

# These are only here because of `--gpus all`:
$ ls -l /usr/lib64/libcuda*
lrwxrwxrwx 1 root root       12 May 25 08:11 /usr/lib64/libcuda.so -> libcuda.so.1
-r-xr-xr-x 1 root root   162552 Mar  6  2024 /usr/lib64/libcuda.so.1
-r-xr-xr-x 1 root root 10524136 Mar  6  2024 /usr/lib64/libcudadebugger.so.1

$ ldd /usr/lib64/libcuda.so.1
        linux-vdso.so.1 (0x00007fffcc7ec000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00007f1db1213000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f1db1757000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f1db1752000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1db1761000)
```

The `libcuda.so` symlink I think is added by the nvidia container runtime when starting the container (_where it implicitly mounts the actual files + wsl driver files for cuda_).

Without the `--gpus all` or equivalent to do that setup, I don't think the container can actually interact with the GPU at runtime (_even if you ensure that compat `libcuda` was resolved_), unless you run it out of a container after building a binary. Thus that extra 150MB in the nvidia images `cuda/compat/` dir presumably isn't relevant?

`ldd` can resolve to that if needed via `LD_LIBRARY_PATH` adding that location, or doing what nvidia already does for their other cuda libs location by adding an entry into `/etc/ld.so.conf.d/`

```bash
echo "/usr/local/cuda/compat" >> /etc/ld.so.conf.d/nvidia.conf
# Refresh paths so the dynamic loader / libc interpreter can resolve it (eg: via `ldd`):
ldconfig
```
