### ISSUE TITLE
PTX JIT compile error?

### ISSUE THREAD

**Issue by jianshu93** [coreylowman/cudarc#278]
Hello Team,

called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_INVALID_PTX, "a PTX JIT compilation failed"). I have  cuda v12.1.1

GPU information below:

Wed Jul 17 11:52:35 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-PCIE-40GB          On  |   00000000:C1:00.0 Off |                    0 |
| N/A   34C    P0             43W /  250W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

the code is this: 

    // setup GPU device
    let gpu = CudaDevice::new(0).unwrap();
    // compile ptx
    let ptx = Ptx::from_src(CUDA_KERNEL_MY_STRUCT);
    gpu.load_ptx(
        ptx,
        "cuda_kernel",
        &["cuda_kmer_bit_pack_mmhash", "cuda_kmer_t1ha2"],
    )
    .unwrap();
    let gpu = &gpu;

Any idea?

Thanks,

Jianshu

**Comment by coreylowman** [comment]
Will need to know what `CUDA_KERNEL_MY_STRUCT` is to provide help. Is it a path? Contents of a precompiled ptx?

**Comment by jianshu93** [comment]
Yes exactly, a path for ptx:

const CUDA_KERNEL_MY_STRUCT: &str = include_str!(concat!(env!("OUT_DIR"), "/cuda_kmer_hash.ptx"));
Sorry for the missing part.

Jianshu

**Comment by coreylowman** [comment]
Cool thank looks fine, it might be an issue with how the ptx is formed. What command are you using to compile it?

**Comment by coreylowman** [comment]
I would double check that your arch/code values in build.rs result in ptx that can run on your gpu. You can also manually inspect the result of the nvcc command and try to load that in to ensure it's working properly

**Comment by jianshu93** [comment]
Hi Thanks,

This is the build.rs:

extern crate bindgen;
extern crate cc;

use std::{env, path::PathBuf, process::Command};

use bindgen::CargoCallbacks;
use regex::Regex;

fn main() {
    if cfg!(feature = "cuda-sketch") {
        // Tell cargo to invalidate the built crate whenever files of interest changes.
        println!("cargo:rerun-if-changed={}", "cuda");

        let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

        // build the cuda kernels
        let cuda_src = PathBuf::from("src/cuda_kernel.cu");
        let ptx_file = out_dir.join("cuda_kmer_hash.ptx");

        // Specify the desired architecture version.
        // Check: https://developer.nvidia.com/cuda-gpus
        // let arch = "compute_86"; // For example, using SM 8.6 (Ampere architecture).
        // let code = "sm_86"; // For the same SM 8.6 (Ampere architecture).
        let arch = "compute_89"; // For example, using SM 8.9 (Ada Lovelace architecture).
        let code = "sm_89"; // For the same SM 8.9 (Ada Lovelace architecture).

        let nvcc_status = Command::new("nvcc")
            .arg("-ptx")
            .arg("-o")
            .arg(&ptx_file)
            .arg(&cuda_src)
            .arg(format!("-arch={}", arch))
            .arg(format!("-code={}", code))
            .status()
            .unwrap();

        assert!(
            nvcc_status.success(),
            "Failed to compile CUDA source to PTX."
        );

        // The bindgen::Builder is the main entry point
        // to bindgen, and lets you build up options for
        let bindings = bindgen::Builder::default()
            // The input header we would like to generate
            // bindings for.
            .header("src/cuda_kernel.h")
            // Tell cargo to invalidate the built crate whenever any of the
            // included header files changed.
            .parse_callbacks(Box::new(CargoCallbacks))
            // we use "no_copy" and "no_debug" here because we don't know if we can safely generate them for our structs in C code (they may contain raw pointers)
            .no_copy("*")
            .no_debug("*")
            // Finish the builder and generate the bindings.
            .generate()
            // Unwrap the Result and panic on failure.
            .expect("Unable to generate bindings");

        // we need to make modifications to the generated code
        let generated_bindings = bindings.to_string();

        // Regex to find raw pointers to float and replace them with CudaSlice<f32>
        // You can copy this regex to add/modify other types of pointers, for example "*mut i32"
        let pointer_regex = Regex::new(r"\*mut f32").unwrap();
        let modified_bindings = pointer_regex.replace_all(&generated_bindings, "CudaSlice<f32>");

        // Write the bindings to the $OUT_DIR/bindings.rs file.
        let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
        std::fs::write(out_path.join("bindings.rs"), modified_bindings.as_bytes())
            .expect("Failed to write bindings");
    }
}


I am new to Cuda, not sure whether this is consistent with my A100 machine, since I know the code was only tested against RTX 4090, this could be the reason, the sm is different for different device?

Thanks,

Jianshu

**Comment by jianshu93** [comment]
It seems it is the arch and code is different.

Thanks,

Jianshu
