### ISSUE TITLE
Add Mutex<CudaModule> to CudaDevice for true JIT

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/cudarc#3]
Currently all cuda modules must be specified in the device builder for CudaDevice. This means you can't add any cuda modules after you've built the CudaDevice object.

It would be nice to be able to add a new CudaModule that was compiled on the fly during forward/backward pass, but that would require mutating the CudaDevice even though it's passed by reference.

unclear how this interacts with #10

**Comment by M1ngXU** [comment]
?

**Comment by coreylowman** [comment]
Updated description

**Comment by coreylowman** [comment]
Probably not at first, this is low priority
