### ISSUE TITLE
alloc (without memsetting to 0) should be public

### ISSUE THREAD

**Issue by M1ngXU** [coreylowman/cudarc#54]
can this function be public?
https://github.com/coreylowman/cudarc/blob/2785abba641f3bff4234e0aa70542deab6f67c86/src/driver/safe.rs#L388

Sometimes i know that i'll overwrite/initialize the memory, but memsetting 2GB-3GB before is rather a waste of time.

**Comment by coreylowman** [comment]
Yeah that's fair, and I think many of the dfdx kernels could be moved to using this instead of memsetting 0s. I initially kept it as private just to be on the safer side, but I think since it's marked as unsafe, that should be enough

**Comment by M1ngXU** [comment]
yes ok, on the weekend i'll try to create a PR to fix the issues i created (54-57)
