### ISSUE TITLE
`sync_copy_from` - also accept vector

### ISSUE THREAD

**Issue by M1ngXU** [coreylowman/cudarc#55]
A function that also accepts a vector would be great as the cudaslice-sizes might be dynamic and it then requires more boilerplate code to actually create a correctly sized slice.

**Comment by M1ngXU** [comment]
or actually returning a vector would be great too

**Comment by coreylowman** [comment]
Does there is `dev.take_async` which takes a Vec, and `sync_release` for returning a vec, do those work?

**Comment by M1ngXU** [comment]
hmm, but what if you only want to copy it out and not destroy the slice? also, i don't think that the function names are very clear ...

**Comment by coreylowman** [comment]
Yeah good point. Any suggestions for naming? Definitely open to suggestions!

**Comment by M1ngXU** [comment]
`sync_copy_into_vec` 😅

**Comment by M1ngXU** [comment]
maybe add the documentation label & rename this issue (or close this one and create a new one?)
