### ISSUE TITLE
copy from `CudaView`

### ISSUE THREAD

**Issue by M1ngXU** [coreylowman/cudarc#56]
Sometimes you only need a specific part of a `CudaSlice` and copying from a `CudaView` would be very useful (and why can you only slice with a `RangeFrom`?)

**Comment by coreylowman** [comment]
Can you give example of copying in that manner?

I initially did RangeFrom to make it clear that there is no concept of length for CudaViews. Perhaps with what you are thinking about (copying from CudaView) we could add length and then make the range more generic.

**Comment by M1ngXU** [comment]
if i have a large CudaSlice but only want to copy let's say 100 elements out of it (first 100), then you would have to copy the whole slice and slice the slice you just copied out ...

**Comment by coreylowman** [comment]
This is needed for the stack operation in dfdx - notably you allocate enough space for all the tensors you are stacking, then copy values into sub views
