### ISSUE TITLE
NvrtcLoadingError when using precompiled ptx

### ISSUE THREAD

**Issue by M1ngXU** [coreylowman/cudarc#61]
_Sometimes_ i get this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NvrtcLoadingError { key: "cuda", cuda: DriverError(CUDA_ERROR_INVALID_PTX, "a PTX JIT compilation failed") }'
```
though just recompiling rust (not nvcc) works

**Comment by coreylowman** [comment]
Very weird, can you post source code of the kernel/program you're using?

**Comment by M1ngXU** [comment]
This actually happens with many different source codes ...
If i encounter a smaller source code (currently it's 500 lines of copy paste) with the same issue, i'll post it here.

**Comment by coreylowman** [comment]
I'm going to close this, feel free to reopen if you find a reproducible example
