### ISSUE TITLE
`take_async` should only accept `Send` or `Sync` types

### ISSUE THREAD

**Issue by M1ngXU** [coreylowman/cudarc#70]
I accidently passed `&mut u8` instead of `u8` and got weird errors. The data of the borrow can't be ensured to be valid and probably can't be accessed too. Not sure weather we have to restrict `T` to `Send` or `Sync` (or maybe even something else).

**Comment by coreylowman** [comment]
You mean you passed `Vec<&mut u8>`? Can you post minimal example/errors?

**Comment by M1ngXU** [comment]
there is no error, it's just if you have `CudaSlice<&mut u8>` but your kernel code accepts `unsigned char`, then you will have weird values
