### ISSUE TITLE
Use default stream instead of a new stream per CudaDevice

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/cudarc#74]
Instantiating multiple devices creates multiple streams, and there is tricky synchronization problems between them.

**Comment by M1ngXU** [comment]
is it generally a problem to synchronize multiple devices?

**Comment by M1ngXU** [comment]
and isn't the default stream non-async (but only for non-explicit async ops?)

**Comment by coreylowman** [comment]
By device in description I meant cudarc::CudaDevice. Each of these will have its own stream at the moment
