### ISSUE TITLE
cuRAND fails when generating an odd number of values

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/cudarc#9]
Apparently this is all expected according to their documentation. This crate should find away around this short coming of their host api.

**Comment by M1ngXU** [comment]
maybe generate ((n + 1) / 2) * 2 number then?
if the number is even, then n = 2m => ((2m + 1) / 2) * 2 = m * 2 = 2m
if the number is odd,  then n = 2m + 1 => ((2m + 1 + 1) / 2) * 2 = (m + 1) * 2 = 2m + 2 (even)

or just use if then else?

**Comment by coreylowman** [comment]
Okay I tried some different logic for if the number of values is odd, but got some weird alignment errors.

A really hacky way I might move forward with is to ALWAYS allocate an even number of values. So in the case where you have an array with an odd number of values, there would be an extra value hanging out at the end unused to round it out.

**Comment by M1ngXU** [comment]
so basically generate if n is odd, then generate n + 1 numbers and truncate the vec length (didn’t find the location in the code, so not sure what the output is). but i’d say that that’s a good solution

**Comment by coreylowman** [comment]
Yeah exactly - will probably want to add `fn malloc_async_even` to result.rs (https://github.com/coreylowman/cudarc/blob/main/src/driver/result.rs#L266), and then move to using that here https://github.com/coreylowman/cudarc/blob/main/src/cudarc.rs#L228

**Comment by M1ngXU** [comment]
ok - do you think it's worth for me to look into the code, because i understand basically nothing 😅

**Comment by coreylowman** [comment]
If you have time and interest, sure! I can help review code or answer questions.

**Comment by M1ngXU** [comment]
ok thx! i'll have a look at it in the next few days. any recommendations of what to read before/where to start with?

**Comment by coreylowman** [comment]
Relevant CUDA documentation:
- cuRAND host api overview: https://docs.nvidia.com/cuda/curand/host-api-overview.html#host-api-overview
- cuRAND host api docs: https://docs.nvidia.com/cuda/curand/group__HOST.html#group__HOST
- CUDA Driver api allocation function: https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MALLOC__ASYNC.html#group__CUDA__MALLOC__ASYNC_1g13413273e84a641bce1929eae9e6501f

The functions that have a requirement on even number of values are the log normal & normal generation functions:
- [curandGenerateLogNormal](https://docs.nvidia.com/cuda/curand/group__HOST.html#group__HOST_1g3569cc960eb1a31357752fc813e21f49)
- [curandGenerateLogNormalDouble](https://docs.nvidia.com/cuda/curand/group__HOST.html#group__HOST_1g300c31530c8b461ca89f1e0232a6f05f)
- [curandGenerateNormal](https://docs.nvidia.com/cuda/curand/group__HOST.html#group__HOST_1gb9280e447ef04e1dec4611720bd0eb69)
- [curandGenerateNormalDouble](https://docs.nvidia.com/cuda/curand/group__HOST.html#group__HOST_1g046759ff9b6bf8dafc9eaae04917dc8e)

I.e. they all say:
> CURAND_STATUS_LENGTH_NOT_MULTIPLE if the number of output samples is not a multiple of the quasirandom dimension, or **is not a multiple of two for pseudorandom generators**

**Comment by M1ngXU** [comment]
ok thanks, i'll have a look into this

**Comment by M1ngXU** [comment]
ok, i (finally) installed everything

**Comment by M1ngXU** [comment]
A simple solution would be
`pub type Array<N, const A: usize> = [N; (A + 1) / 2 * 2];`
instead of
`[N; A]`

**Comment by coreylowman** [comment]
@M1ngXU i'm actually thinking that we won't use cuda rng apis to start with for dfdx. Notably, all random numbers with be generated on CPU and then copied to GPU. while this isn't as efficient as possible it enables reproducibility across both cpu & cuda. this will make testing a breeze, and we don't have to worry about things like this bug.

**Comment by M1ngXU** [comment]
> @M1ngXU i'm actually thinking that we won't use cuda rng apis to start with for dfdx. Notably, all random numbers with be generated on CPU and then copied to GPU. while this isn't as efficient as possible it enables reproducibility across both cpu & cuda. this will make testing a breeze, and we don't have to worry about things like this bug.

ok, and since generating rng is done once, not much time should be lost

**Comment by coreylowman** [comment]
Won't fix this bug since it's with the underlying library, and as stated we won't even be using cuRAND.
