### ISSUE TITLE
Remove dependency on find_cuda_helper

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/cudarc#91]
To reduce dependencies

**Comment by M1ngXU** [comment]
is it really necessary? isn't the dep small anyway?

**Comment by coreylowman** [comment]
It's a small one, but every dependency adds up. We can see how much time it actually saves by removing it.

I'd also like to fix and issue that I have every time I use GPUs on cloud.lambdalabs, which is I need to run
```
sudo ln -s /usr/lib/cuda /usr/local/cuda
```

for find_cuda_helper to find it.

**Comment by M1ngXU** [comment]
Ah ok, makes sense. Didn't know that such a small dependency adds that much
compile time 😅

**Comment by quietlychris** [comment]
I believe I ran into the same issue with `find_cuda_helper` as well on a Pop!_OS installation (basically Ubuntu) regarding the cuda path not being one of the defaults in that crate anyway, which took a bit minute to track down.
