### ISSUE TITLE
Docs.rs build fails on 0.9.0

### ISSUE THREAD

**Issue by nkoppel** [coreylowman/cudarc#96]
This seems to be related to changes to build.rs that require a cuda installation to exist, specifically [here](https://github.com/coreylowman/cudarc/blob/b1000014c1cf1314ab0afbcbd366f55ab2c2a2c6/build.rs#LL16C4-L19). This should be fixable with a `#[cfg(not(doc))]` and a version bump.

[Here](https://docs.rs/crate/cudarc/0.9.0/builds/763035) is the build log of the failing build.

**Comment by coreylowman** [comment]
Resolved with https://github.com/coreylowman/cudarc/commit/f06387548531bfe19699cb42ee0cdec8dc50c862
