### ISSUE TITLE
Keep track of ordinal in CudaDevice & expose a reference to it

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/cudarc#98]
```rust
struct CudaDevice {
    ...
    ordinal: usize
}

fn ordinal(&self) -> &usize {
    &self.ordinal
}
```

**Comment by M1ngXU** [comment]
(why?)

**Comment by coreylowman** [comment]
This is related to multi GPU support - to check whether a tensor needs to be copied to a different GPU, we need to know what ordinal both devices have. Currently I don't think this is possible
