### ISSUE TITLE
Add CudaBytes

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/cudarc#99]
Would look like this:
```rust
#[derive(Debug)]
pub struct CudaBytes {
    pub(crate) cu_device_ptr: sys::CUdeviceptr,
    pub(crate) num_bytes: usize,
    pub(crate) device: ...
}
```

And this can be unsafely transformed into a CudaSlice<T>

**Comment by coreylowman** [comment]
Not much, only that it wouldn't have a type generic on it. Although now that I think about it, we probably don't need this. What we really need is a way to reinterpret a `CudaSlice<T>` into another type.

What i'd like to do for workspaces is store a `CudaSlice<u8>` on Cuda, and then grab a view of those bytes as another type.

So maybe something like:
```rust
let mut workspace: CudaSlice<u8> = ...;
let _: &CudaView<f32> = workspace.reinterpretted(n)
```

**Comment by M1ngXU** [comment]
ah ok; why not directly store it as f32 (dtype)?

**Comment by M1ngXU** [comment]
> Because it needs to support f16, f32, and f64 dtypes, and the device won't necessarily know which one since it doesn't have a dtype generic on it (and I'd prefer not to add it).

but doesn’t e.g. conv2d has a dtype? and the workspace would have the same dtype, wouldn’t it? or where do you plan to use it

**Comment by coreylowman** [comment]
https://github.com/coreylowman/dfdx/compare/main...workspace

**Comment by M1ngXU** [comment]
> 

hmm, ok, so everything runs on a single stream/one cudnn handle?
